name: Publish to NPM

on:
  push:
    branches: [main]


permissions:
  contents: write
  id-token: write # Required for OIDC and trusted publishing

jobs:
  release:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          # We need the full history for version calculation
          fetch-depth: 0
          token: ${{ secrets.MY_GH_RELEASE_TOKEN }}

      - name: Install Node.js per package.json
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Update npm # To ensure npm 11.5.1 or later is installed for Trusted publishing
        shell: bash
        run: npm install -g npm@latest

      - name: Publish release (using OIDC trusted publishing)
        shell: bash
        run: npm publish --access public