name: Publish to NPM

on:
  push:
    branches: [main]


permissions:
  contents: write
  id-token: write # Required for OIDC and trusted publishing

jobs:
  call-publish:
    uses: ./.github/workflows/reusable-publish.yml
